stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    # - echo "Building the project..."
    - ./build.sh
test_job:
  stage: test
  script:
    - ./test.sh

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."