stages:
  - default
  - build
  - test
  - deploy

default:
  stage: default
  image: node:latest
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    
build_job:
  stage: build
  script:
    - echo "Building the project..."
    - echo "Identification des dépendances obsolètes"
    - pnpm outdated --format json > reports/outdated-dependencies.json
    - echo "Identification des dépendances vulnérables"
    - pnpm audit --json  > reports/vulnerable-dependencies.json   
    - echo "Installation des dépendances du projet"
    - pnpm install
    - echo "Type checking" 
    - pnpm vue-tsc --noEmit
    - echo "Installation des dépendances du projet"
    - pnpm vite build
    - echo "Analyse statique"
    - pnpm eslint .


test_job:
  stage: test
  script:
    - echo "Execution des tests"
    - pnpm vitest run

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."