stages:
  - build
  - static-typing
  - lint
  - test
  - publish

variables:
  VERSION : "0.0.0"

default:
  image: node:latest
  cache: &global_cache
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    policy: pull
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install

static-typing-job:
  stage: static-typing
  script:
    - pnpm type-check
  when: manual # permet de faire ce stage manuellement

lint-job:
  stage: lint
  script:
    - pnpm lint

build-job:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - pnpm build 
  artifacts:
    name: $(VERSION)
    paths:
      - /dist

test-job:
  stage: test
  script:
    - pnpm test