stages:
  - default
  - test
  - build
  - deploy

default:
  stage: default
  image: node:latest
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install # install dependencies
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
    
build_job:
  stage: build
  script:
    # - echo "Building the project..."
    - ./build.sh

test_job:
  stage: test
  script:
    - ./test.sh
    
deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."